# 📘 NumPy Basics

In [259]:
import numpy as np


### Creating Arrays

In [260]:
a = np.array([1, 2, 3]) # 1D array 1X3 matrix
b = np.array(
            [[1, 2],
              [3, 4]]
            ) # 2D array 2 x 2 matrix
c=np.array(
            [[[1, 2],
              [3, 4]],
             [[5, 6],
              [7, 8]]]
            ) # 3D array 2 x 2 x 2 matrix
# 2 3D = 4D 2 X 2X 2X 2 matrix
print("1D:", a)
print("2D:\n", b)
print("3D:\n", c)


1D: [1 2 3]
2D:
 [[1 2]
 [3 4]]
3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [261]:
print("Shape:", c.shape)
print("Size:", c.size)
print("Data Type:", c.dtype)
print("Dimension:", c.ndim)

Shape: (2, 2, 2)
Size: 8
Data Type: int32
Dimension: 3


### Array Initialization

In [262]:
print(np.eye(N=3,M=3,k=1 ))



[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [263]:
x=np.zeros((2,3)) # 2 X3 array of Zeros
print("Zeros:\n", x)
x=x+3
print("After adding 3:\n", x)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
After adding 3:
 [[3. 3. 3.]
 [3. 3. 3.]]


In [264]:
# print(np.zeros((2,3))) # 2 X3 array of Zeros
# # [[0. 0. 0.]
# # [0. 0. 0.]]
 
# print(np.ones((3,3)))
# #[[1. 1. 1.]
# #  [1. 1. 1.]
# #  [1. 1. 1.]]
# print(np.eye(3))
# for i in range(1, 11, 2): #(starting, ending -1, step)
#     print(i, end=" ")
    
# print(np.arange(0, 10, 2))
x=np.linspace(1,10, 5)
print(x)

[ 1.    3.25  5.5   7.75 10.  ]


### Indexing and Slicing

In [265]:
arr = np.array([10, 20, 30, 40, 50])  # slicing (start index, stop index -1, step size) everything separted by colons
    #            0   1   2   3   4  positive index
    #           -5  -4  -3  -2  -1  negative
print(arr[1])
print(arr[-3:-1])  # last element

m = np.array([[1, 2, 3], [4, 5, 6]])
#                0           1
#               0  1  2    0  1  2
print(m[1][2])
# print(m[:,1])

20
[30 40]
6


In [266]:
arr = np.array([10, 20, 30, 40, 50])  # slicing (start index, stop index -1, step size) everything separted by colons
    #            0   1   2   3   4  positive index
    #           -5  -4  -3  -2  -1  negative

print(arr[-5:-1:2])  # last element

[10 30]


In [ ]:
k=np.array([
            [
                [[1],[2]],
                [[3],[4]]
             ],
            [
                [[5],[6]],
                [[7],[8]]
             ]
           ]
            )
print(k.ndim)
j=[[[
    [1]
    ]]]
# print(k[0][1][0])
# print(k[1][1][0])
# print(k[1,0,1]) # reversing the 1st dimension

4


### Mathematical Operations

In [268]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Add:", a + b)
print("Multiply:", a * b)
print("Square:", a ** 2)
print("Dot:", np.dot(a, b))

Add: [5 7 9]
Multiply: [ 4 10 18]
Square: [1 4 9]
Dot: 32


### Statistical Functions

In [269]:
arr = np.array([1, 2, 3, 4, 5])
print("Mean:", np.mean(arr))
print("Std Dev:", np.std(arr))
print("Sum:", np.sum(arr))

Mean: 3.0
Std Dev: 1.4142135623730951
Sum: 15


# 📘 Pandas Basics

In [270]:
import pandas as pd

### Creating Series

In [271]:
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
print(s)

a    10
b    20
c    30
dtype: int64


### Creating DataFrame

In [272]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "Score": [85, 90, 95]
}
print(data)
df = pd.DataFrame(data)
print(df)
df.to_excel("output1.xlsx", index=False)
print("File created")

{'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35], 'Score': [85, 90, 95]}
      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
File created


### Reading and Writing Files

In [284]:
# df = pd.read_csv("new.csv")
# print(df)
# df.to_excel("output.xlsx", index=False)


import pandas as pd
df1=pd.read_excel("sample_data.xlsx")
print(df1)

  Month  Sales  Expenses  Profit
0   Jan    200       150      50
1   Feb    220       180      40
2   Mar    250       160      90
3   Apr    210       190      20


### Exploring Data

In [ ]:
df=pd.read_excel("sample_data.xlsx")
df.head()  # Display the first few rows
df.tail(1)  # Display the last 3 rows
df.shape # Get the shape of the DataFrame
df.columns  # Get the column names
df.describe()  # Get summary statistics
df.info()  # Get information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Month     4 non-null      object
 1   Sales     4 non-null      int64 
 2   Expenses  4 non-null      int64 
 3   Profit    4 non-null      int64 
dtypes: int64(3), object(1)
memory usage: 256.0+ bytes


### Selecting and Filtering

In [299]:

# print(df[["Month", "Sales"]])
print(df[df["Sales"] <= 220])

  Month  Sales  Expenses  Profit
0   Jan    200       150      50
1   Feb    220       180      40
3   Apr    210       190      20


### Sorting and Grouping

In [304]:
# print(df.sort_values(by="Sales", ascending=True))
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "Score": [85, 90,95]
}

df = pd.DataFrame(data)
print(df)
print("--------------------------------------------")
df.groupby(["Name","Age"])["Score"].sum()  # Group by 'name' and calculate the mean of 'score'

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
--------------------------------------------


Name     Age
Alice    25     85
Bob      30     90
Charlie  35     95
Name: Score, dtype: int64

In [309]:
# print(ord("a"))
# print(ord("B"))
print("a" < "A")
print("a" is not "A")

False
True


<>:4: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:4: SyntaxWarning: "is not" with a literal. Did you mean "!="?
C:\Users\Nandhan\AppData\Local\Temp\ipykernel_17772\1761852422.py:4: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  print("a" is not "A")


### Handling Missing Data

In [316]:
df=pd.read_excel("sample_data.xlsx")
df
#df.info()
#df.isnull()
df.fillna(3)  # Fill NaN values with 0

#


Month  Sales  Expenses  Profit
0   Jan  200.0     150.0    50.0
1   Feb  220.0       3.0    40.0
2   Mar    3.0     160.0    90.0
3   Apr  210.0     190.0     3.0

### Apply Functions

In [318]:
df["Bonus"] = df["Sales"].apply(lambda x: x * 0.10)
print(df)

# n=pd.Series([1, 2, 3, 4, 5])

# def mul(x):
#     print(x*2)
# for i in n:
#     mul(i)
    
# n.apply(lambda x: x * 4)  # Apply a function to each element

  Month  Sales  Expenses  Profit  Bonus
0   Jan  200.0     150.0    50.0   20.0
1   Feb  220.0       NaN    40.0   22.0
2   Mar    NaN     160.0    90.0    NaN
3   Apr  210.0     190.0     NaN   21.0


In [ ]:
lambda x: x * 0.10  # Anonymous function

### Merging DataFrames

In [279]:
df1 = pd.DataFrame({"ID": [1, 2], "Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"ID": [1, 2], "Marks": [90, 80]})

merged = pd.merge(df1, df2, on="ID")
print(merged)

   ID   Name  Marks
0   1  Alice     90
1   2    Bob     80
